cfg:
  seed: 42
  name: I-JEPA_chestxray-h5_resnet50_IN1kCFG_predL3K3_Maskmixed_lr0.01_wd0.01_bs64_4GPU
  artifacts_root: artifacts/pretrain_lightly/ijepacnn_chestxray-h5
  mask:
    strategy: mixed
    mutli_block_kwargs:
      aspect_ratio:
      - 0.75
      - 1.5
      enc_mask_scale:
      - 1.0
      - 1.0
      min_keep: 5
      num_enc_blocks: 1
      num_pred_blocks: 4
      pred_mask_scale:
      - 0.15
      - 0.2
    mixed_mutli_block_ratio: 0.75
  mask_ratio: 0.6
  backbone:
    name: resnet50
    pretrained_weights: null
    kwargs:
      global_pool: ''
  predictor:
    n_layers: 3
    kernel_size: 3
    dw_sep_conv: true
  use_projection_head: false
  data:
    dataset_name: chestxray-h5
    num_workers: 8
  trainer:
    max_epochs: 201
    devices: auto
    accelerator: gpu
    precision: bf16
    accumulate_grad_batches: 4
    overfit_batches: 1
  optimizer:
    batch_size: 64
    lr: 0.01
    weight_decay: 0.01
    cosine_warmpup_sched: true
    lr_warmup_epochs: 10
    exclude_norm_and_bias_from_wd: false
    wd_schedule: false
  wandb: true
